### ISSUE TITLE
[Bug] Reconnect Smoke Grenade

### ISSUE THREAD

**Issue by axl303** [rehlds/ReGameDLL_CS#879]
One of the many smoke bugs is that if you throw it and retry/reconnect the smoke doesn't appear.
The thing I noticed is that the smoke cloud doesn't appear, but the grenade itself is still on the ground (it appears little with very tiny smoke coming out of it). 
My logic (ofc stupid as always) is that if grenade is still on the ground, maybe there is a way to force the smoke cloud? 
Should this be related to gamedll and corrected by the server or?
Reported by perforator here: https://github.com/ValveSoftware/halflife/issues/2940

**Comment by dystopm** [comment]
Problem is, Smoke effect duration is fixed on client-side, and due to this, if we send another Smoke effect to a joining player, it will last longer than the original one sent before he connects. It can be done only if the grenade exploded, maybe, 10 seconds before, but it will last longer anyway for him. @s1lentq a potential client-side improvement, making Smoke duration a parameter in PlaybackEvent

**Comment by SergeyShorokhov** [comment]
The smoke cloud is created with an event, and the server has no way to control the duration (as @dystopm  said above). ReGameDLL_CS doesn't have a fix for this at the moment.

> есть способ создать облако дыма?

I made a separate solution in the form of AMXModX plugin. 
https://github.com/SergeyShorokhov/ServerSide_SmokeNade_AMXX
